# -*- coding: utf-8 -*-
"""Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfdgD1u645YJelAVsCF5yoLyHacHcaZg
"""

import pandas as pd
import numpy as np

credits= pd.read_csv("/tmdb_5000_credits.csv")

movies= pd.read_csv("/tmdb_5000_movies.csv")

credits.head()

movies.head()

print("Credits:",credits.shape)
print("Movies Dataframe:",movies.shape)

credits_column_renamed= credits.rename(index=str,columns={"movie_id":"id"})
movies_merge= movies.merge(credits_column_renamed, on='id')
movies_merge.head()

movies_cleaned= movies_merge.drop(columns=['homepage','title_x','title_y','status','production_countries'])
movies_cleaned.head()

movies_cleaned.info()

v=movies_cleaned['vote_count']
R=movies_cleaned['vote_average']
C=movies_cleaned['vote_average'].mean()
m=movies_cleaned['vote_count'].quantile(0.70)

movies_cleaned.head()

weighted_average = (v / (v + m)) * R + (m / (v + m)) * C
movies_cleaned['weighted_average'] = weighted_average

weighted_ranking=movies_cleaned.sort_values('weighted_average',ascending=False)
weighted_ranking[['original_title','vote_count','vote_average','weighted_average','popularity']].head(10)

import matplotlib.pyplot as plt
import seaborn as sns
weight_average=weighted_ranking.sort_values('weighted_average',ascending=False)
plt.figure(figsize=(12,6))
axis1=sns.barplot(x=weight_average['weighted_average'].head(10),y=weight_average['original_title'].head(10),data=weight_average, palette='viridis')
plt.xlim(0,10)
plt.title('Top 10 Movies by weighted average score', weight='bold')
plt.xlabel('Weighted Average Score (0-10)', weight='bold')
plt.ylabel('Movie Title', weight='bold')
plt.savefig('best_movies_weighted_0-10.png')

movies_cleaned['popularity'].head()

popularity  = movies_cleaned.sort_values('popularity',ascending=False)
plt.figure(figsize=(12,6))
ax=sns.barplot(x=popularity['popularity'].head(10),y=popularity['original_title'].head(10),palette='deep')
plt.title('Top 10 Movies by Popularity', weight='bold')
plt.xlabel('Popularity Score', weight='bold')
plt.ylabel('Movie Title', weight='bold')
plt.savefig('best_movies_popularity.png')

from sklearn.preprocessing import MinMaxScaler
scaling= MinMaxScaler()
movie_scaled=scaling.fit_transform(movies_cleaned[['weighted_average','popularity']])
movie_normalised=pd.DataFrame(movie_scaled,columns=['weighted_average','popularity'])
movie_normalised.head()

movies_cleaned['normalized_weight'] = movie_normalised['weighted_average']
movies_cleaned['normalized_popularity'] = movie_normalised['popularity']
movies_cleaned['score'] = movies_cleaned['normalized_weight']*0.5 + movies_cleaned['normalized_popularity']*0.5
movies_scored=movies_cleaned.sort_values(['score'],ascending=False)
movies_scored[['original_title','normalized_weight','normalized_popularity','score']].head(20)

scored=movies_cleaned.sort_values('score',ascending=False)
plt.figure  (figsize=(16,6))
ax=sns.barplot(x=scored['score'].head(10), y=scored['original_title'].head(10), data=scored, palette='deep')
plt.title('Best Rated & Most Popular Movies', weight='bold')
plt.xlabel('Score', weight='bold')
plt.ylabel('Movie Title', weight='bold')
plt.savefig('best_movies_score.png')
